---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.app.namespaceDev }}
  annotations:
    openshift.io/description: "Dev Namespace"
    openshift.io/display-name: "Dev Namespace"
  labels:
    argocd.argoproj.io/managed-by: {{ .Values.argocdNamespace }}
