---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-ui-app-source
  namespace: {{ .Values.tektonNamespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
