apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterserviceversions-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterserviceversions-reader
subjects:
- kind: User
  name: {{ .Values.namespacePermissions.user }}

