---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vote-app-api-pipeline
  namespace: {{ .Values.tektonNamespace }}
spec:
  params:
  - name: git-repo-url
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: vote-app-api-pipeline-
    spec:
      params:
      - name: SOURCE_GIT_URL
        value: $(tt.params.git-repo-url)
      - name: SOURCE_GIT_REVISION
        value: $(tt.params.git-revision)
      pipelineRef:
        name: vote-app-api-pipeline
      workspaces:
      - name: app-source
        persistentVolumeClaim:
          claimName: workspace-api-app-source

