apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-api
  name: vote-api
spec:
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: vote-api
  sessionAffinity: None
  type: ClusterIP
