---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.argocdNamespace }}
  annotations:
    openshift.io/description: "ArgoCD GitOps Namespace"
    openshift.io/display-name: "ArgoCD GitOps Namespace"
