{{- range .Values.repos }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.argocdNamespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: {{ .type }}
  url: {{ .url }}
  username: {{ .username }}
  password: {{ .password }}
---
{{- end }}
